### ISSUE TITLE
Yläkoulun tilastoissa keskihajonta sekoitettu keskipoikkeamaan

### ISSUE THREAD

**Issue by timopera** [avoimet-oppimateriaalit-ry-arkisto/vapaa-matikka#20]
Hei!

Sivulla 49 lukee "keskihajonta ilmoittaa, kuinka kaukana muuttujan arvot keskimäärin ovat keskiarvosta".
Mielestäni kirjassa on virhe, sillä keskipoikkeama on tämä "keskimääräinen poikkeama". 

Esimerkiksi normaalijakaumassa 1 keskihajonnan sisään keskiarvosta kuuluu n. 68% ja 2 keskihajonnan sisään n.95% havainnoista. Esimerkiksi lukujen 0,1,2,3,4 ja 5 keskipoikkeama on 1,5 ja keskihajonta n. 1,71.

Kirjaan voisi lisätä erillisen kappaleen tutkimaan keskihajontaa, sillä se on tilastollisista hajontaluvuista tietääkseni eniten käytössä. Esimerkiksi kasvukäyrässä kahden keskihajonnan poikkeama on merkittävä. Keskihajonnan laskeminen taas on työlästä. Lisävaikeuden tuo otoskeskihajonnan hieman erillainen kaava.

**Comment by NVI** [comment]
Vapaa matikka -sarjalla on eri tekijät kuin Avoin matematiikka -sarjalla, joten en pysty kommentoimaan tekijöiden puolesta.

En kuitenkaan näe lainauksessa mitään virhettä, sillä kysehän on vain metriikan valinnasta, eikä missään ilmeisesti viitata siihen, että tässä käytettäisiin (joskin toki yläastelaisille tutuinta) L1-metriikkaa, joka siis vastaisi keskipoikkeamaa.

Keskihajonta tosiaankin on hajontaluvuista käytetyin ja siksi on luonnollista käsitellä juuri sitä, eikä vaikkapa keskipoikkeamaa tai varianssia. Keskihajontaan liittyvät tehtävät näyttäisivät olevan tarkoitettuja laskimen toiminnolla tehtäviksi, joten kaavaan ei tässä ole tarvetta puuttua.

**Comment by wedrawde** [comment]
Koetan itse antaa täsmällisiä määritelmiä. Pedagogisesti on mielestäni
perusteltua poistaa epämääräisyydet ja tulkinnanvaraisuudet sumeista
määritelmistä,  Ongelma syntyy tietty jos neliö ja neliöjuuri käsite tuntuu
vaikealta.  Tosin opetan lapsille kertolaskun yhteydessä
neliöjuurikäsitettä lukuna joka kerrottuna itsensä kanssa on annettu luku.
Helppo 4 ja 9 kohdalla.

Eli ehdotan tällaista lähestymistapaa.

Populaation keskihajonta mittaa hajontaa. Mittarina se on tarkemmin kuin
esim. muutujien vaihteluväli joka ainoastaan huomioi suurimman ja pienimmän
arvon.  Tarkkaan ottaen keskihajonta saadaan laskemalla neliöjuuri
muutujien ja niiden keskiarvon erotuksen neliöiden keskiarvosta.

Tässä vaiheessa näytän esimerkin.

Esimerkiksi  muuttujien 1 ja 9
- keskiarvo on:(1+9)/2=5

ja
- keskihajonta on
  neliöjuuri(((1-5)(1-5)+(9-5)(9-5))/2)=neliöjuuri((16+16)/2) = 4

Otoksen kohdalla jaetaan keskiarvo pienemmällä luvulla eli n-1:llä n:n
sijasta koska otoksen keskihajonta on yleensä pienempi kuin koko
populaation keskihajonta ja tällä korjauksella saadaan parempi arvio
populaation keskihajonnalle.

t. Edward K.

2014-08-25 17:50 GMT+03:00 Niko Ilomäki notifications@github.com:
